name: "@pinnacle0/web-ui CI"

env:
    CI: true

on:
    push:
        branches: [master]
        paths:
            - packages/web-ui/**
            - .github/workflows/pkg-web-ui-ci.yml

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
                  check-latest: true
            - uses: actions/cache@v2
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - run: yarn install
            - run: yarn workspace @pinnacle0/web-ui run build
