name: "@pinnacle0/eslint-plugin CI"

env:
    CI: true

on:
    push:
        branches: [master]
        paths:
            - packages/eslint-plugin/**
            - .github/workflows/pkg-eslint-plugin-ci.yml

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  check-latest: true
            - uses: actions/cache@v2
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - run: yarn install
            - run: yarn workspace @pinnacle0/eslint-plugin run build
